services:
  mongodb:
    image: mongo:7-jammy
    
    container_name: mongodb
    
    ports:
      - "27007:27017"
    
    volumes:
      - mongodata:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    
    networks:
      - backend
    
    restart: always

<<<<<<< HEAD
  pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector
    ports:
      - "5400:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    environment:

      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    networks:
      - backend
    restart: always

=======
>>>>>>> d73c391 (Merge pull request #1 from Mu-Magdy/feat-semantic-search)
networks:
  backend:

volumes:
  mongodata:
<<<<<<< HEAD
  pgvector_data:
=======
>>>>>>> d73c391 (Merge pull request #1 from Mu-Magdy/feat-semantic-search)
